version: '3.3'
services:
  web: #name of the container
    build: .
    ports:
    - "127.0.0.1:8000:8000"
    command: python ./manage.py runserver
    volumes:
      - .:/app #map the volume--anything changed here is reflected in the container
